[package]
name = "axdot"
version = "0.1.0"
authors = ["xrelkd 46590321+xrelkd@users.noreply.github.com"]
edition = "2018"

[dependencies]
fs_extra = "1"
serde = { version = "1", features = ["derive"] }
serde_yaml = "0.8"
structopt = "0.3"
snafu = "0.6"
