[tasks.format]
command = "rustup"
args = ["run", "nightly", "cargo", "fmt"]

[tasks.build]
command = "cargo"
args = ["build"]
dependencies = ["format"]

[tasks.build-release]
command = "cargo"
args = ["build", "--release"]
dependencies = ["format"]

[tasks.test]
command = "cargo"
args = ["test"]

[tasks.generate-completions]
script = [
'''
rm -rf completions

mkdir -p completions/{bash-completion/completions,fish/completions,zsh/site-functions}

./target/release/axdot completions bash > "completions/bash-completion/completions/axdot"
./target/release/axdot completions fish > "completions/fish/completions/axdot.fish"
./target/release/axdot completions zsh > "completions/zsh/site-functions/_axdot"
'''
]
dependencies = ["build-release"]

[tasks.clean]
command = "cargo"
args = ["clean"]

