complete -c axdot -n "__fish_use_subcommand" -s h -l help -d 'Prints help information'
complete -c axdot -n "__fish_use_subcommand" -s V -l version -d 'Prints version information'
complete -c axdot -n "__fish_use_subcommand" -f -a "version" -d 'Shows current version'
complete -c axdot -n "__fish_use_subcommand" -f -a "completions" -d 'Shows shell completions'
complete -c axdot -n "__fish_use_subcommand" -f -a "init" -d 'Generates empty configuration'
complete -c axdot -n "__fish_use_subcommand" -f -a "apply" -d 'Applies from configuration file'
complete -c axdot -n "__fish_use_subcommand" -f -a "dry-apply" -d 'Shows what would be applied'
complete -c axdot -n "__fish_use_subcommand" -f -a "help" -d 'Prints this message or the help of the given subcommand(s)'
complete -c axdot -n "__fish_seen_subcommand_from version" -s h -l help -d 'Prints help information'
complete -c axdot -n "__fish_seen_subcommand_from version" -s V -l version -d 'Prints version information'
complete -c axdot -n "__fish_seen_subcommand_from completions" -s h -l help -d 'Prints help information'
complete -c axdot -n "__fish_seen_subcommand_from completions" -s V -l version -d 'Prints version information'
complete -c axdot -n "__fish_seen_subcommand_from init" -s h -l help -d 'Prints help information'
complete -c axdot -n "__fish_seen_subcommand_from init" -s V -l version -d 'Prints version information'
complete -c axdot -n "__fish_seen_subcommand_from apply" -l config -d 'Configuration file path'
complete -c axdot -n "__fish_seen_subcommand_from apply" -s r -l replace -d 'Replaces files/folders if they already exist'
complete -c axdot -n "__fish_seen_subcommand_from apply" -s h -l help -d 'Prints help information'
complete -c axdot -n "__fish_seen_subcommand_from apply" -s V -l version -d 'Prints version information'
complete -c axdot -n "__fish_seen_subcommand_from dry-apply" -l config -d 'Configuration file path'
complete -c axdot -n "__fish_seen_subcommand_from dry-apply" -s r -l replace -d 'Replaces files/folders if they already exist'
complete -c axdot -n "__fish_seen_subcommand_from dry-apply" -s h -l help -d 'Prints help information'
complete -c axdot -n "__fish_seen_subcommand_from dry-apply" -s V -l version -d 'Prints version information'
complete -c axdot -n "__fish_seen_subcommand_from help" -s h -l help -d 'Prints help information'
complete -c axdot -n "__fish_seen_subcommand_from help" -s V -l version -d 'Prints version information'
