# syntax=docker/dockerfile:1.4

FROM sccache AS sccache

# This is the build stage for axdot. Here we create the binary in a temporary image.
FROM rust AS builder

COPY --from=sccache /usr/bin/sccache /usr/bin/sccache

RUN <<EOF
#!/usr/bin/env bash

apt-get update
apt-get install -y wget unzip

wget -O /tmp/protoc.zip https://github.com/protocolbuffers/protobuf/releases/download/v23.2/protoc-23.2-linux-x86_64.zip
unzip -o -d /usr/ /tmp/protoc.zip
rm -fv /tmp/protoc.zip

protoc --version

EOF

ARG RUSTC_WRAPPER="/usr/bin/sccache"
ARG AWS_ACCESS_KEY_ID
ARG AWS_SECRET_ACCESS_KEY
ARG SCCACHE_BUCKET
ARG SCCACHE_ENDPOINT
ARG SCCACHE_S3_USE_SSL

WORKDIR /build
COPY . /build

RUN cargo build --locked --release

# This is the 2nd stage: a very small image where we copy the axdot binary."
FROM distroless as axdot

COPY --from=builder /build/target/release/axdot /usr/bin/axdot

ENTRYPOINT [ "/usr/bin/axdot" ]
